[build]
builder = "nixpacks"

[build.nixpacks]
buildCmd = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
